alias bundle="docker-compose run --rm app bundle"
alias rspec="docker-compose run --rm app bundle exec rspec"
alias rake="docker-compose run --rm app bundle exec rake"
alias rails="docker-compose run --rm app bundle exec rails"
alias ruby="docker-compose run --rm app bundle exec ruby"
